{
 "title": "Connector Performance Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Performance Testing: Source Connectors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Kafka Connect Source: Poll batch Avg Time (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_source_task_metrics_poll_batch_avg_time_ms",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Kafka Connect Source Producer: Outgoing Byte Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_outgoing_byte_rate{job=\"connect\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Kafka Connect Source: Write Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_source_task_metrics_source_record_write_total",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Kafka Connect Source: Write Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_source_task_metrics_source_record_write_rate",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Performance Testing: Sink Connectors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Kafka Connect Consumer Per Connector: Incoming Byte Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_incoming_byte_rate{job=\"connect\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Sink Connectors: Put Batch Avg Time (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_sink_task_metrics_put_batch_avg_time_ms",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Sink Connectors: Send Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_sink_task_metrics_sink_record_send_rate",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Sink Connectors: Send Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_sink_task_metrics_sink_record_send_total",
     "legendFormat": "{{connector}}"
    }
   ]
  }
 ]
}